### ISSUE TITLE
AttributeError: no such child: {AnetApi/xml/v1/schema/AnetApiSchema.xsd}messages

### ISSUE THREAD

**Issue by logandg** [AuthorizeNet/sdk-python#93] opened 2018-01-07 03:18 UTC
When trying to create an accept js payment transaction we're occasionally getting this error:

AttributeError: no such child: {AnetApi/xml/v1/schema/AnetApiSchema.xsd}messages

We've used the example given here almost verbatim: 
https://github.com/AuthorizeNet/sample-code-python/blob/master/PaymentTransactions/create-an-accept-payment-transaction.py

Looking at all the python samples I can't find a good example of what to do when messages doesn't exist on response.

**Comment by Sapbasu15** [comment] 2018-02-22 10:48
@logandg if the request is well formed and successful there should be something in the messages under the response object. Please verify the request send to the API and its response. You can also explicitly check messages for None in response object before accessing. Let us know if the issue is still persistent.

**Comment by chsriniv9** [comment] 2018-05-18 11:13
Closing based on the suggestion provided by @Sapbasu15 
Please feel free to open the issue if needed.

**Closed by chsriniv9** 2018-05-18 11:13 UTC

**Comment by amitbehra123** [comment] 2023-11-27 17:00
@Sapbasu15 we are still getting this issue if we do payment through card outside us.
