### ISSUE TITLE
MixedContentError: Invalid non-element content

### ISSUE THREAD

**Issue by jigneshept** [AuthorizeNet/sdk-python#61] opened 2016-08-09 07:31 UTC
Hi,

We used this SDK in a live environment, We got following error while performs an operation to create customer profiles since all things are well in the form. So, I did not understand why it will give error. Please reply as soon as possible.

Other things I want to know why you have applied you own _XSDLocation in the SDK and Current SDK in Beta development status. So, When It will be ready or stable.

  File "/usr/local/lib/python2.7/dist-packages/pyxb/binding/basis.py", line 2094, in **init**
    self.extend(args, _from_xml=from_xml, _location=location)
  File "/usr/local/lib/python2.7/dist-packages/pyxb/binding/basis.py", line 2579, in extend
    [ self.append(_v, **kw) for _v in value_list ]
  File "/usr/local/lib/python2.7/dist-packages/pyxb/binding/basis.py", line 2506, in append
    self._appendWildcardElement(value)
  File "/usr/local/lib/python2.7/dist-packages/pyxb/binding/basis.py", line 2572, in _appendWildcardElement
    raise pyxb.MixedContentError(self, value)
MixedContentError: Invalid non-element content

**Comment by sunnyrajrathod** [comment] 2016-08-09 09:03
Hi @jigneshept ,
Can you let us know the sdk version that you are using?
We will be updating the _XSDLocation with the next release.

Thanks.

**Comment by jigneshept** [comment] 2016-08-09 09:18
We are using authorizenet-1.0.11.

**Comment by jigneshept** [comment] 2016-08-09 09:23
Hi @sunnyrajrathod,

Is this sdk is ready to use with Live environment ?

**Comment by sunnyrajrathod** [comment] 2016-08-09 11:40
Hi @jigneshept, 
yes you can use the sdk in Live environment.
This issue seems to be related to specific request/response. Since, we are not able to reproduce this, we will need some more details regarding the request or response that you are receiving. Can you send the request and response(after masking sensitive data) to sunnyrajrathod@gmail.com. 
Also, did you try any other API? If yes, are you getting a similar error there as well?

**Comment by jigneshept** [comment] 2016-08-09 11:52
Hi @sunnyrajrathod,

We did not have request/response file but We have following that line where I got error. We are trying to create customer profile but it gives above error while evaluate following line.
 
Q : did you try any other API?
And : No, We did not tried any other API.

I hope you are solve it quickly.
Thanks, 

createCustomerProfile.profile = apicontractsv1.customerProfileType(self.env['ir.sequence'].sudo().next_by_code('payment.profile.seq') or 'New', "%s %s"%(post.get('billing_first_name'),post.get('billing_last_name')), post.get('billing_email'))

**Comment by sunnyrajrathod** [comment] 2016-08-09 12:22
Thanks @jigneshept ,
We were able to reproduce the issue. The first parameter while constructing customerProfileType is merchantCustomerId, and it is expected to be string. It seems you are passing as integer. 
Try again by sending it as a string.

**Comment by jigneshept** [comment] 2016-08-09 13:45
Hi @sunnyrajrathod,

We already passed merchantCustomerId and other things in string that you have told but still some time getting errors of Invalid non-element content.

Thanks.

**Comment by KrzychuPiro** [comment] 2016-08-24 11:02
Hi @sunnyrajrathod 

I have the same problem with Python SDK v1.0.12. Previously I used v1.0.7 and everything worked fine. This problem occurs at time to time in over 50% cases. 

My code is based on AuthorizeNet sample-code-python:
```
createCustomerProfile = apicontractsv1.createCustomerProfileRequest()
createCustomerProfile.merchantAuthentication = self.get_merchant()
createCustomerProfile.profile = apicontractsv1.customerProfileType(self.user.email.split('@')[0] + str(randint(0, 10000)), self.user.name, self.user.email)
```

**Comment by sunnyrajrathod** [comment] 2016-08-26 05:17
Hi @krzkolek / @jigneshept,
We tried executing this call multiple times, over both python 2.7 and 3.5 environments. We are still not able to reproduce this, with correct string parameters. Only way we are getting the mentioned errors is when any of the parameters are not string.
Is there even a slight chance that the parameters you are sending might not be string in your cases?
Can you try this instead:
`createCustomerProfile.profile = apicontractsv1.customerProfileType(self.user.email.split('@')[0] + str(randint(0, 10000)), str(self.user.name), str(self.user.email))`

**Comment by krzkolek** [comment] 2016-08-26 13:30
Hi @jigneshept 

I tried your hint but the problem still occurs. 
I attached a copy of Django debug site with this error and example values which I used. For the same values sometimes work fine - it's a lottery.
[MixedContentError.zip](https://github.com/AuthorizeNet/sdk-python/files/439348/MixedContentError.zip)

Thanks.

**Comment by jigneshept** [comment] 2016-08-29 04:46
Hi @sunnyrajrathod / @krzkolek 

I agree with @krzkolek that for the some value sometimes it's work fine. I have replaced latest SDK with previous (lower version of SDK) and that is working well. I did not get any problems.

Thanks.

**Comment by NPGiorgi** [comment] 2017-04-06 15:33
@jigneshept I'm having the same issue. Which version worked for you? I know this happen some time ago but maybe you still can get the version

**Comment by danielatdattrixdotcom** [comment] 2017-05-17 22:11
@NPGiorgi I just started getting hit with this on 1.0.12, updated to 1.0.14 and so far the issues have gone away. For what it's worth the element that was causing it in my case was during operations with a CIM and and seemingly on the return data since it the string causing an issue was the CIM Profile "Customer ID" which I have formatted like: abc-123

**Comment by Sapbasu15** [comment] 2017-12-05 11:34
@NPGiorgi , can you please confirm if this issue is resolved in your case for the latest sdk release ?

**Comment by Sapbasu15** [comment] 2017-12-14 11:24
Thank you for raising this issue. We have had some releases since the issue was raised, and we hope that these updates have resolved your asks. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.

**Closed** 2017-12-14 11:55 UTC
